version: "3"
services:
  homeassistant:
    container_name: jkbms
    image: jkbms_mqtt
    devices:
    environment:
      - mqtt_server=192.168.111.1
      - mqtt_user=
      - mqtt_pass=
      - mqtt_port = 1883
      - mqtt_topic = jkbms
      - modbus_ip = 192.168.2.229
      - modbus_port = 502
      - modbus_unit = 1
      - query_seconds = 10
      - homeassistant_mqtt_topic = homeassistant
      - debug_values = true

